name: Test notebooks

on:
    schedule:
      - cron: '0 0 * * 6'  # Run at midnight on Saturdays
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v4
          with:
            version: "latest"

        - name: Set up Python ${{ matrix.python-version }}
          run: uv python install ${{ matrix.python-version }}

        - name: Setup Graphviz
          uses: ts-graphviz/setup-graphviz@v1

        - name: Install Python packages
          run: uv sync --group dev

        - name: Run Notebook Test
          run: uv run ./scripts/test_notebooks.sh
